# Generated by Django 4.2.7 on 2023-12-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=10)),
                ('created', models.DateField(default='2023-12-28')),
                ('due_date', models.DateField(default='2023-12-28')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
