# Generated by Django 4.2.7 on 2024-01-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bg_color', models.CharField(choices=[('#5549A3', 'Purple'), ('#6d6c6c', 'Grey'), ('#2323a0', 'Blue'), ('#940D23', 'Red'), ('#179213', 'Green')], default='#5549A3', max_length=20)),
            ],
        ),
    ]
