# Generated by Django 5.0.1 on 2024-01-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_event_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='UTC', max_length=63),
        ),
    ]
