# Generated by Django 5.0.1 on 2024-01-21 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_event_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timezone',
        ),
    ]
