# Generated by Django 4.2.7 on 2024-01-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_poll_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(max_length=105),
        ),
    ]
