# Generated by Django 2.2.7 on 2019-11-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20191120_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bg_color',
            field=models.CharField(choices=[('#5549A3', 'Purple'), ('#6d6c6c', 'Grey'), ('#2323a0', 'Blue'), ('#940D23', 'Red'), ('#179213', 'Green')], default='#5549A3', max_length=20),
        ),
    ]
